package com.agelousis.kotlinmultiplatform.theme

import androidx.compose.ui.graphics.Color

val WhiteTwo = Color(0xFFFFFFFF)
val Butterscotch = Color(color = 0xFFFCB947)
val Petrol = Color(color = 0xFF005a73)
val Steel = Color(color = 0xFF8A8A8D)
val DarkGreySecondary = Color(color = 0xFF424242)
val Turquoise = Color(color = 0xFF43CB8D)
val LightButterscotch = Color(color = 0xFFF7CE5B)
val LightPurple = Color(color = 0xFF736BBD)
val Peach = Color(color = 0xFFEf767A)
val LightBlue = Color(color = 0xFF7d9fff)
val SlimyGreen = Color(color = 0xFF418D18)
val ColumbiaBlue = Color(color = 0xFFCFD6E6)
val LavenderWeb = Color(color = 0xFFE7EFF9)
val QuickSilver = Color(color = 0xFFA2A2A2)
val BlueSapphire = Color(color = 0xFF0D6C84)
val PetrolGreen = Color(color = 0xFF005A74)
val PaleAqua = Color(color = 0xFFCFD6E6)
val AliceBlue = Color(color = 0xFFE7EFF9)
val SpanishGray = Color(color = 0xFF9E9E9E)
val CelticBlueColors = arrayOf(
    Color(color = 0xFF2E78BF),
    Color(color = 0xFF2A78B8)
)
val LightPink = Color(color = 0xFFFED1EF)
val LightGreyBlue = Color(color = 0xFFE3EDF0)
val CelticBlue = Color(color = 0xFF2E78BF)
val SonicSilver = Color(color = 0xFF757575)
val GoGreen = Color(color = 0xFF12af5b)
val PastelOrange = Color(color = 0xFFfcb947)
val Jet = Color(color = 0xFF343434)
val SunsetOrange = Color(color = 0xFFf65e5e)
val MediumAquamarine = Color(color = 0xFF5DD39E)
val SteelBlue = Color(color = 0xFF348AA7)
val ToolboxColor = Color(color = 0xFF736BBD)
val OceanGreen = Color(color = 0xFF43CB8E)
val ViridianGreen = Color(color = 0xFF068D9D)
val GreenSheen = Color(color = 0xFF75C1B3)
val JetStreamColor = Color(color = 0xFFC5DECD)
val DutchWhite = Color(color = 0xFFF1DDBB)
val QueenBlue = Color(color = 0xFF456990)
val VerdigrisColor = Color(color = 0xFF49BEAA)
val BrightGray = Color(color = 0xFFE6F0F2)
val DimGray = Color(color = 0xFF6A696A)
val YellowOrange = Color(color = 0xFFF8AB49)
val MyrtleGreen = Color(color = 0xFF337165)
val GraniteGrayColor = Color(color = 0xFF616161)
val Coral = Color(color = 0xFFFF875A)
val MistyRose = Color(color = 0xFFFFE7DE)
val BrightGraySecondary = Color(color = 0xFFEEEEEE)
val SilverSand = Color(color = 0xFFC6C6C6)
val Topaz = Color(color = 0xFFFFD277)
val TopazTrue = Color(color = 0xFF00A69C)
val MetallicSeaweed = Color(color = 0xFF0A8095)
val CulturedColor = Color(color = 0xFFF5F5F5)
val CulturedPaleColor = Color(color = 0xFFF3F7F8)
val MidnightGreen = Color(color = 0xFF004D62)
val RichBlack = Color(color = 0xFF073642)
val DarkPink = Color(color = 0xFFF05374)
val BlueViolet = Color(color = 0xFF7419E3)
val OutrageousOrange = Color(color = 0xFFFB6A44)
val CarolinaBlue = Color(color = 0xFF4EA2DF)
val Begonia = Color(color = 0xFFFF7075)
val Cornsilk = Color(color = 0xFFFFF5E0)
val MetallicSilver = Color(color = 0xFFA7A9AC)
val Gray = Color(color = 0xFFBDBDBD)
val BrightNavyBlue = Color(color = 0xFF1c7ed4)
val Jasmine = Color(color = 0xFFFED47E)
val Gainsboro = Color(color = 0xFFDCDCDC)
val DarkSilver = Color(color = 0xFF707070)
val DarkJungleGreen = Color(color = 0xFF061D24)
val ChineseWhite = Color(color = 0xFFE0E0E0)
val MindaroColor = Color(color = 0xFFDBFE77)
val PalePink = Color(color = 0xFFF2DCDC)
val BloodAnimalColor = Color(color = 0xFFAA1313)
val DarkPetrol = Color(color = 0xFF004D62)
val CatalinaBlue = Color(color = 0xFF0C1C71)
val IndigoBlue = Color(color = 0xFF132597)
val PersianBlue = Color(color = 0xFF1b2ec2)
val PalatinateBlue = Color(color = 0xFF1733D5)
val TurquoiseSurf = Color(color = 0xFF00bdd3)
val Platinum = Color(color = 0xFFE2E2E2)
val OuterSpace = Color(color = 0xFF444444)
val ColorAccent = Petrol
val EucalyptusColor = Color(color = 0xFF26E2B4)
val LightSeaGreenColor = Color(color = 0xFF1BA2AF)
val LuxuryWhiteColor = Color(color = 0xFFFAFAFA)
val ArcticWhiteColor = Color(color = 0xFFE5EDEF)
val MorningDrizzleColor = Color(color = 0xFFE4EDEE)
val DanishBlueColor = Color(color = 0xFFCDDDE2)
val OceanicTealColor = Color(color = 0xFF0D566A)

val SoftBlue = Color(color = 0xFF4DA1DF)
val WeirdMint = Color(color = 0xFF00BAB3)
val DeepBlue = Color(color = 0xFF0082CB)
val HeavenlyGreenColor = Color(color = 0xFF60bc46)
val LightSeaColor = Color(color = 0xFFE4EEF0)
val gradientColors = listOf(
    Color.Red,
    Color.Magenta,
    Color.Blue,
    Color.Cyan,
    Color.Green,
    Color.Yellow,
    Color.Red
)